# Generated by Django 2.1.7 on 2019-03-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EtimRawDataNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depot_cd', models.CharField(blank=True, max_length=10, null=True)),
                ('dutydate', models.DateField(db_column='dutyDate')),
                ('waybilldate', models.DateTimeField(db_column='waybillDate')),
                ('waybillcollectiondate', models.DateField(db_column='waybillCollectionDate')),
                ('ticketid', models.IntegerField(db_column='ticketId')),
                ('full_amt', models.FloatField(blank=True, db_column='FULL_AMT', null=True)),
                ('full_pax', models.IntegerField(db_column='FULL_PAX')),
                ('routeno', models.CharField(db_column='routeNo', max_length=6)),
                ('empcode', models.CharField(db_column='empCode', max_length=10)),
                ('ticket_bus_no', models.CharField(db_column='TICKET_BUS_NO', max_length=10)),
                ('ttl_tkt_issue', models.FloatField(blank=True, db_column='TTL_TKT_ISSUE', null=True)),
                ('etimticketcodeid', models.IntegerField(db_column='etimTicketCodeId')),
                ('ticketcode', models.CharField(db_column='ticketCode', max_length=2)),
                ('rupee_deno', models.FloatField(blank=True, db_column='RUPEE_DENO', null=True)),
                ('full_tkt', models.CharField(db_column='FULL_TKT', max_length=1)),
                ('bottkt', models.BigIntegerField()),
                ('machineno', models.CharField(db_column='machineNo', max_length=8)),
                ('ticketdate', models.CharField(db_column='ticketDate', max_length=8)),
                ('tickettime', models.CharField(db_column='ticketTime', max_length=8)),
                ('fromstopcode', models.CharField(db_column='fromStopcode', max_length=11)),
                ('frmstopname', models.CharField(db_column='frmStopName', max_length=30)),
                ('tostopname', models.CharField(db_column='toStopname', max_length=30)),
                ('tostopcode', models.CharField(db_column='toStopCode', max_length=11)),
                ('fromstageno', models.CharField(db_column='fromStageNo', max_length=3)),
                ('tostageno', models.CharField(db_column='toStageNo', max_length=3)),
                ('hexwaybillno', models.CharField(db_column='hexwaybillNo', max_length=12)),
                ('tripno', models.IntegerField(db_column='tripNo')),
                ('tripdirection', models.CharField(db_column='tripDirection', max_length=1)),
                ('docketno', models.CharField(db_column='docketNo', max_length=17)),
                ('concessionid', models.IntegerField(db_column='concessionId')),
                ('serialno', models.IntegerField(db_column='serialNo')),
                ('ep_flag', models.CharField(max_length=7)),
                ('sent_flag', models.CharField(max_length=1)),
                ('inserteddate', models.DateTimeField(db_column='insertedDate')),
                ('modifieddate', models.DateTimeField(db_column='modifiedDate')),
            ],
            options={
                'db_table': 'etim_raw_data_new',
                'managed': False,
            },
        ),
    ]
